name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

template: |
  ## What's Changed

  $CHANGES

  **Full diff:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  $CONTRIBUTORS

categories:
  - title: New Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - bug
      - fix
  - title: Maintenance
    labels:
      - chore
      - maintenance
      - refactor
  - title: Documentation
    labels:
      - docs
      - documentation
  - title: Dependencies
    labels:
      - dependencies

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

initial-version: 0.1.0

exclude-labels:
  - skip-changelog
