version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - gosec
    - misspell

  settings:
    errcheck:
      check-type-assertions: true
    gosec:
      excludes:
        - G104
        - G304

  exclusions:
    generated: lax
