services:
  sitegen:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    ports: !override []
    volumes: !override
      - ./content:/content:${CONTENT_VOLUME_MODE:-ro}
      - site-output:/docs
      - ./cert.pem:/cert.pem
