apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sitegen
  namespace: sitegen
  labels:
    app: sitegen
spec:
  rules:
    - host: docs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sitegen
                port:
                  name: http
